//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Automation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SettingApp
    {
        public int Sett_ID { get; set; }
        public string ExpireDate_Host { get; set; }
        public string LoginFTP { get; set; }
        public string FtpUsername { get; set; }
        public string FtpPassword { get; set; }
        public string FtpAddress { get; set; }
    }
}
