//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Automation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Missions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Missions()
        {
            this.Tbl_ReportMission = new HashSet<Tbl_ReportMission>();
        }
    
        public int MissionID { get; set; }
        public Nullable<int> PersonelID_FK { get; set; }
        public string Date_Mission { get; set; }
        public string From_Hours { get; set; }
        public string Until_Hours { get; set; }
        public string Destination { get; set; }
        public string Description { get; set; }
        public string Date_Sumbit { get; set; }
    
        public virtual Tbl_Personels Tbl_Personels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ReportMission> Tbl_ReportMission { get; set; }
    }
}
