//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Automation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Persmissions
    {
        public int PermissionID { get; set; }
        public Nullable<int> UserID_FK { get; set; }
        public Nullable<bool> Users { get; set; }
        public Nullable<bool> Personels { get; set; }
        public Nullable<bool> Mission { get; set; }
        public Nullable<bool> Leaves { get; set; }
        public Nullable<bool> LeavesTime { get; set; }
        public Nullable<bool> Attendance { get; set; }
    
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
