//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Automation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ReportMission
    {
        public int ReportID { get; set; }
        public Nullable<int> PersonelID_FK { get; set; }
        public Nullable<int> MissionID_FK { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ReportDate { get; set; }
    
        public virtual Tbl_Missions Tbl_Missions { get; set; }
        public virtual Tbl_Personels Tbl_Personels { get; set; }
    }
}
