//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Automation.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Attendance_DBEntities : DbContext
    {
        public Attendance_DBEntities()
            : base("name=Attendance_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Attendance> Tbl_Attendance { get; set; }
        public virtual DbSet<Tbl_Leaves> Tbl_Leaves { get; set; }
        public virtual DbSet<Tbl_LeavesTime> Tbl_LeavesTime { get; set; }
        public virtual DbSet<Tbl_Missions> Tbl_Missions { get; set; }
        public virtual DbSet<Tbl_Persmissions> Tbl_Persmissions { get; set; }
        public virtual DbSet<Tbl_Personels> Tbl_Personels { get; set; }
        public virtual DbSet<Tbl_ReportMission> Tbl_ReportMission { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_SettingApp> Tbl_SettingApp { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
    }
}
