//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Automation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Personels()
        {
            this.Tbl_Attendance = new HashSet<Tbl_Attendance>();
            this.Tbl_Leaves = new HashSet<Tbl_Leaves>();
            this.Tbl_LeavesTime = new HashSet<Tbl_LeavesTime>();
            this.Tbl_Missions = new HashSet<Tbl_Missions>();
            this.Tbl_ReportMission = new HashSet<Tbl_ReportMission>();
        }
    
        public int PersonelID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Post { get; set; }
        public string Mobile { get; set; }
        public string Personel_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Attendance> Tbl_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Leaves> Tbl_Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_LeavesTime> Tbl_LeavesTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Missions> Tbl_Missions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ReportMission> Tbl_ReportMission { get; set; }
    }
}
